#!/bin/bash

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
DIR="pokemon_data"


mkdir -p "$DIR"

for p in "${POKEMONS[@]}"; do
    echo "Fetching data for $p..."


    curl -s "https://pokeapi.co/api/v2/pokemon/$p" -o "$DIR/$p.json"


    if [ $? -eq 0 ] && [ -s "$DIR/$p.json" ]; then
        echo "Saved data to $DIR/$p.json "
    else
        echo "Failed to fetch $p" >> errors.txt
    fi

    sleep 1
done
