#!/bin/bash


NAME=$(jq -r '.name' data.json)
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json)


HEIGHT_M=$(awk "BEGIN { printf \"%.1f\", $HEIGHT / 10 }")


WEIGHT_KG=$(awk "BEGIN { printf \"%.0f\", $WEIGHT / 10 }")


TYPE_CAP=$(echo "$TYPE" | sed 's/.*/\u&/')


NAME_CAP=$(echo "$NAME" | sed 's/.*/\u&/')

echo "$NAME_CAP is of type $TYPE_CAP, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_M}m tall."
