#!/bin/bash


NAME=$(jq -r '.name' data.json)
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json)


formatted_height=$(awk "BEGIN { printf \"%.1f\", $HEIGHT / 10 }")


formatted_weight=$(awk "BEGIN { printf \"%.0f\", $WEIGHT / 10 }")


type=$(echo "$TYPE" | sed 's/.*/\u&/')


name=$(echo "$NAME" | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
